"""rename department - CORRECTED VERSION

Revision ID: 1694ecedb24d_corrected
Revises: 51f20aa4768b
Create Date: 2023-08-02 18:19:06.373953

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1694ecedb24d_corrected'
down_revision = '51f20aa4768b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CORRECTED VERSION - use rename_table to preserve data!
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CORRECTED VERSION - rename back to original name
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
