"""rename address - INCORRECT AUTO-GENERATED VERSION

Revision ID: 76f31678b786
Revises: 1694ecedb24d_corrected
Create Date: 2023-08-02 18:52:31.603713

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '76f31678b786'
down_revision = '1694ecedb24d_corrected'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # THIS IS THE INCORRECT VERSION - it drops the column and creates a new one!
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.drop_column('address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # THIS IS ALSO INCORRECT - it tries to recreate the old column name
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('location')
    # ### end Alembic commands ###
