"""rename address - CORRECTED VERSION

Revision ID: 76f31678b786_corrected
Revises: 1694ecedb24d_corrected
Create Date: 2023-08-02 18:52:31.603713

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '76f31678b786_corrected'
down_revision = '1694ecedb24d_corrected'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CORRECTED VERSION - use alter_column to preserve data!
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CORRECTED VERSION - rename back to original column name
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
